spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: HXj22oVU2540zif4gFmn
            client-secret: 5D4Hsx313A
            scope:
              - name
              - email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/naver/callback'
          kakao:
            client-id: ff186d351034c6d3db268df03e7c596a
            client-secret: 6bX9xJgRVwbFUApqPU0fi3nEiWjNY4Cd
            scope:
              - openid
              - profile
              - account_email
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/kakao/callback'
            client-authentication-method: client_secret_post
          # 구글 설정 추가 예시
          google:
            client-id: 589056962488-5211p8t3nk7etdiajjp3qdgg7n4jdi4e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/google/callback'
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id
          # 구글 설정 추가 예시
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://openidconnect.googleapis.com/v1/userinfo"
            user-name-attribute: sub
  profiles:
    include: oauth
  application:
    name: cocktails
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sey
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update


  config:
    import:
      - classpath:/yaml/application-{verification}.yml
      - classpath:/yaml/application-{weather}.yml

server:
  port: 9092
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 860802
    key-alias: selfsigned
  max-http-request-header-size: 65536

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

jwt:
  secret-key: "J6Dfye3LvLpH2EM5B6W9XSn7HURx5Vhsw7pqG9T6moE="

